"""empty message

Revision ID: b910fcbcac87
Revises: 
Create Date: 2023-11-16 21:31:36.409733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b910fcbcac87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['actor_id'])

    with op.batch_alter_table('move_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['movie_id'])

    with op.batch_alter_table('movie_actor_relation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('movie_info', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_info', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('movie_actor_relation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('move_box', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('actor_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
